name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
          - uses: actions/checkout@v4
          - name: Download w64devkit
            run: |
              curl -L https://github.com/raysan5/raylib/releases/download/6.0/raylib-6.0_win64_msvc16.zip -o w64devkit.zip
              7z x w64devkit.zip -oC:\raylib
          - name: Add to PATH
            run: echo "C:\raylib\include" >> $env:GITHUB_PATH
          - name: Build
            run: make
          - uses: actions/upload-artifact@v4
            with:
              name: fclauncher-windows
              path: bin/fclauncher.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependecies
        run: sudo add-apt-repository ppa:texus/raylib && sudo apt update && sudo apt install libraylib5-dev libgl-dev libx11-dev 
      - name: Build
        run: make
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fclauncher-linux
          path: bin/fclauncher
