name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install -y libraylib-dev libgl-dev libx11-dev
      - run: make
      - uses: actions/upload-artifact@v4
        with:
          name: fclauncher-linux
          path: bin/fclauncher

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-raylib
      - shell: msys2 {0}
        run: make
      - uses: actions/upload-artifact@v4
        with:
          name: fclauncher-windows
          path: bin/fclauncher.exe